"""empty message

Revision ID: 0ed858dd11e7
Revises: 9dbf63467c67
Create Date: 2022-04-12 13:27:00.548877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ed858dd11e7'
down_revision = '9dbf63467c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_fund_trace', sa.Column('buy_money', sa.Float(), nullable=True))
    op.add_column('user_fund_trace', sa.Column('sale_amount', sa.Float(), nullable=True))
    op.add_column('user_fund_trace', sa.Column('application_time', sa.DateTime(), nullable=True))
    op.add_column('user_fund_trace', sa.Column('trace_price', sa.Float(), nullable=True))
    op.add_column('user_fund_trace', sa.Column('trace_amount', sa.Float(), nullable=True))
    op.add_column('user_fund_trace', sa.Column('trace_time', sa.DateTime(), nullable=True))
    op.drop_index('ix_user_fund_trace_status', table_name='user_fund_trace')
    op.drop_column('user_fund_trace', 'last_day_profit')
    op.drop_column('user_fund_trace', 'sale_price')
    op.drop_column('user_fund_trace', 'amount')
    op.drop_column('user_fund_trace', 'buy_price')
    op.drop_column('user_fund_trace', 'current_price')
    op.drop_column('user_fund_trace', 'agrent_time')
    op.drop_column('user_fund_trace', 'all_profit')
    op.drop_column('user_fund_trace', 'sale_time')
    op.drop_column('user_fund_trace', 'buy_time')
    op.drop_column('user_fund_trace', 'count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_fund_trace', sa.Column('count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_fund_trace', sa.Column('buy_time', mysql.DATETIME(), nullable=True))
    op.add_column('user_fund_trace', sa.Column('sale_time', mysql.DATETIME(), nullable=True))
    op.add_column('user_fund_trace', sa.Column('all_profit', mysql.FLOAT(), nullable=True))
    op.add_column('user_fund_trace', sa.Column('agrent_time', mysql.DATETIME(), nullable=True))
    op.add_column('user_fund_trace', sa.Column('current_price', mysql.FLOAT(), nullable=True))
    op.add_column('user_fund_trace', sa.Column('buy_price', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_fund_trace', sa.Column('amount', mysql.FLOAT(), nullable=True))
    op.add_column('user_fund_trace', sa.Column('sale_price', mysql.FLOAT(), nullable=True))
    op.add_column('user_fund_trace', sa.Column('last_day_profit', mysql.FLOAT(), nullable=True))
    op.create_index('ix_user_fund_trace_status', 'user_fund_trace', ['status'], unique=False)
    op.drop_column('user_fund_trace', 'trace_time')
    op.drop_column('user_fund_trace', 'trace_amount')
    op.drop_column('user_fund_trace', 'trace_price')
    op.drop_column('user_fund_trace', 'application_time')
    op.drop_column('user_fund_trace', 'sale_amount')
    op.drop_column('user_fund_trace', 'buy_money')
    # ### end Alembic commands ###
