"""empty message

Revision ID: 33253f908907
Revises: 76c823c15e12
Create Date: 2022-04-12 22:24:20.655954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33253f908907'
down_revision = '76c823c15e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_fund_hold',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fund_id', sa.Integer(), nullable=True),
    sa.Column('fund_code', sa.String(length=64), nullable=True),
    sa.Column('fund_name', sa.String(length=64), nullable=True),
    sa.Column('hold_num', sa.Float(), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('buy_price_time', sa.DateTime(), nullable=True),
    sa.Column('buy_amount', sa.Float(), nullable=True),
    sa.Column('buy_time', sa.DateTime(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('price_time', sa.DateTime(), nullable=True),
    sa.Column('current_amount', sa.Float(), nullable=True),
    sa.Column('current_profit', sa.Float(), nullable=True),
    sa.Column('lastday_profit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['fund.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_fund_hold_fund_id'), 'user_fund_hold', ['fund_id'], unique=False)
    op.create_index(op.f('ix_user_fund_hold_user_id'), 'user_fund_hold', ['user_id'], unique=False)
    op.add_column('fund', sa.Column('current_price', sa.Float(), nullable=True))
    op.add_column('fund', sa.Column('price_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fund', 'price_time')
    op.drop_column('fund', 'current_price')
    op.drop_index(op.f('ix_user_fund_hold_user_id'), table_name='user_fund_hold')
    op.drop_index(op.f('ix_user_fund_hold_fund_id'), table_name='user_fund_hold')
    op.drop_table('user_fund_hold')
    # ### end Alembic commands ###
