"""empty message

Revision ID: 86f491e82be7
Revises: d3e30168edfc
Create Date: 2022-04-12 19:16:57.996200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f491e82be7'
down_revision = 'd3e30168edfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_fund_trace', sa.Column('price_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_fund_trace', 'price_time')
    # ### end Alembic commands ###
