"""empty message

Revision ID: 9dbf63467c67
Revises: 
Create Date: 2022-04-12 11:42:02.500246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9dbf63467c67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fund_temp')
    op.add_column('user_fund_trace', sa.Column('agrent_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_fund_trace', 'agrent_time')
    op.create_table('fund_temp',
    sa.Column('fund_code', mysql.TEXT(), nullable=True),
    sa.Column('fund_name', mysql.TEXT(), nullable=True),
    sa.Column('source_rate', mysql.TEXT(), nullable=True),
    sa.Column('rate', mysql.TEXT(), nullable=True),
    sa.Column('min_pn', mysql.TEXT(), nullable=True),
    sa.Column('syl_1y', mysql.TEXT(), nullable=True),
    sa.Column('syl_6m', mysql.TEXT(), nullable=True),
    sa.Column('syl_3m', mysql.TEXT(), nullable=True),
    sa.Column('syl_1m', mysql.TEXT(), nullable=True),
    sa.Column('shares_positions', mysql.TEXT(), nullable=True),
    sa.Column('net_worth_trend', mysql.TEXT(), nullable=True),
    sa.Column('ac_worth_trend', mysql.TEXT(), nullable=True),
    sa.Column('grand_total', mysql.TEXT(), nullable=True),
    sa.Column('rate_in_similar_type', mysql.TEXT(), nullable=True),
    sa.Column('rate_in_similar_present', mysql.TEXT(), nullable=True),
    sa.Column('fluctuation_scale', mysql.TEXT(), nullable=True),
    sa.Column('holder_structure', mysql.TEXT(), nullable=True),
    sa.Column('asset_allocation', mysql.TEXT(), nullable=True),
    sa.Column('performance_evaluation', mysql.TEXT(), nullable=True),
    sa.Column('current_fund_manager', mysql.TEXT(), nullable=True),
    sa.Column('buy_sedemption', mysql.TEXT(), nullable=True),
    sa.Column('swithSameType', mysql.TEXT(), nullable=True),
    sa.Column('stock_codes', mysql.TEXT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
