"""empty message

Revision ID: ac8d4c749857
Revises: bc6942098957
Create Date: 2022-04-16 10:20:29.972998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac8d4c749857'
down_revision = 'bc6942098957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_profit', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('current_time', sa.DateTime(), nullable=True))
    op.drop_column('user', 'last_day_profit')
    op.drop_column('user', 'all_fund_profit')
    op.add_column('user_fund_hold', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('user_fund_hold', sa.Column('last_price', sa.Float(), nullable=True))
    op.add_column('user_fund_hold', sa.Column('last_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_fund_hold', 'last_time')
    op.drop_column('user_fund_hold', 'last_price')
    op.drop_column('user_fund_hold', 'cost')
    op.add_column('user', sa.Column('all_fund_profit', mysql.FLOAT(), nullable=True))
    op.add_column('user', sa.Column('last_day_profit', mysql.FLOAT(), nullable=True))
    op.drop_column('user', 'current_time')
    op.drop_column('user', 'last_profit')
    # ### end Alembic commands ###
