"""empty message

Revision ID: bc6942098957
Revises: 33253f908907
Create Date: 2022-04-13 12:48:04.466353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc6942098957'
down_revision = '33253f908907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_fund_hold', sa.Column('sale_flag', sa.Integer(), nullable=True))
    op.add_column('user_fund_hold', sa.Column('deal_flag', sa.Integer(), nullable=True))
    op.add_column('user_fund_trace', sa.Column('trace_num', sa.Float(), nullable=True))
    op.add_column('user_fund_trace', sa.Column('trace_total', sa.Float(), nullable=True))
    op.drop_column('user_fund_trace', 'trace_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_fund_trace', sa.Column('trace_amount', mysql.FLOAT(), nullable=True))
    op.drop_column('user_fund_trace', 'trace_total')
    op.drop_column('user_fund_trace', 'trace_num')
    op.drop_column('user_fund_hold', 'deal_flag')
    op.drop_column('user_fund_hold', 'sale_flag')
    # ### end Alembic commands ###
