"""empty message

Revision ID: bf2eaa31ad89
Revises: 0ed858dd11e7
Create Date: 2022-04-12 15:54:38.675239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf2eaa31ad89'
down_revision = '0ed858dd11e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_fund_trace', sa.Column('sale_number', sa.Float(), nullable=True))
    op.drop_column('user_fund_trace', 'sale_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_fund_trace', sa.Column('sale_amount', mysql.FLOAT(), nullable=True))
    op.drop_column('user_fund_trace', 'sale_number')
    # ### end Alembic commands ###
