"""empty message

Revision ID: e3188f3f1f57
Revises: a93e0ba1fd91
Create Date: 2022-04-16 20:52:01.308049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3188f3f1f57'
down_revision = 'a93e0ba1fd91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_fund_hold', 'sale_flag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_fund_hold', sa.Column('sale_flag', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
